### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by okt-limonikas** [ts-factory/bublik-ui#213]
- [ ] Add log link from report
- [ ] Fix key undefined on run page
- [ ] Fix error handling
- [ ] Disable source button if failed to fetch
